cls
call KENSSharp.exe -c n "art_b.unc" "art_b.nem"
call KENSSharp.exe -c e "map0_b.unc" "map0_b.eni"
call KENSSharp.exe -c e "map1_b.unc" "map1_b.eni"
call KENSSharp.exe -c e "map2_b.unc" "map2_b.eni"
call KENSSharp.exe -c e "map3_b.unc" "map3_b.eni"
call KENSSharp.exe -c e "map4_b.unc" "map4_b.eni"
call KENSSharp.exe -c e "map5_b.unc" "map5_b.eni"
call KENSSharp.exe -c e "map6_b.unc" "map6_b.eni"
call KENSSharp.exe -c e "map7_b.unc" "map7_b.eni"
call KENSSharp.exe -c e "map8_b.unc" "map8_b.eni"
call KENSSharp.exe -c e "map9_b.unc" "map9_b.eni"
call KENSSharp.exe -c e "map10_b.unc" "map10_b.eni"
call KENSSharp.exe -c e "map11_b.unc" "map11_b.eni"
call KENSSharp.exe -c e "map12_b.unc" "map12_b.eni"

copy /y "art_b.nem" "..\..\..\..\conimodes\foxyboo\art_b.nem"
copy /y "map0_b.eni" "..\..\..\..\conimodes\foxyboo\map1_b.eni"
copy /y "map1_b.eni" "..\..\..\..\conimodes\foxyboo\map2_b.eni"
copy /y "map2_b.eni" "..\..\..\..\conimodes\foxyboo\map3_b.eni"
copy /y "map3_b.eni" "..\..\..\..\conimodes\foxyboo\map4_b.eni"
copy /y "map4_b.eni" "..\..\..\..\conimodes\foxyboo\map5_b.eni"
copy /y "map5_b.eni" "..\..\..\..\conimodes\foxyboo\map6_b.eni"
copy /y "map6_b.eni" "..\..\..\..\conimodes\foxyboo\map7_b.eni"
copy /y "map7_b.eni" "..\..\..\..\conimodes\foxyboo\map8_b.eni"
copy /y "map8_b.eni" "..\..\..\..\conimodes\foxyboo\map9_b.eni"
copy /y "map9_b.eni" "..\..\..\..\conimodes\foxyboo\map10_b.eni"
copy /y "map10_b.eni" "..\..\..\..\conimodes\foxyboo\map11_b.eni"
copy /y "map11_b.eni" "..\..\..\..\conimodes\foxyboo\map12_b.eni"
copy /y "map12_b.eni" "..\..\..\..\conimodes\foxyboo\map13_b.eni"
copy /y "pal_b.bin" "..\..\..\..\conimodes\foxyboo\pal_b.bin"
REM pause