cls
call KENSSharp.exe -c n "bsod_gg-art1.unc" "bsod_gg-art1.nem"
call KENSSharp.exe -c n "bsod_sms1-art1.unc" "bsod_sms1-art1.nem"
call KENSSharp.exe -c n "bsod_sms2-art1.unc" "bsod_sms1-art2.nem"
call KENSSharp.exe -c e "bsod_gg1-mapFG.unc" "bsod_gg1-mapFG.eni"
call KENSSharp.exe -c e "bsod_gg2-mapFG.unc" "bsod_gg2-mapFG.eni"
call KENSSharp.exe -c e "bsod_sms1-mapFG.unc" "bsod_sms1-mapFG.eni"
call KENSSharp.exe -c e "bsod_sms2-mapFG.unc" "bsod_sms2-mapFG.eni"
copy /y "bsod_gg-art1.nem" "..\..\..\..\..\..\_gamemode\winBSOD\bsod_gg-art1.nem"
copy /y "bsod_sms1-art1.nem" "..\..\..\..\..\..\_gamemode\winBSOD\bsod_sms1-art1.nem"
copy /y "bsod_sms2-art1.nem" "..\..\..\..\..\..\_gamemode\winBSOD\bsod_sms2-art1.nem"
copy /y "bsod_gg1-mapFG.eni" "..\..\..\..\..\..\_gamemode\winBSOD\bsod_gg1-mapFG.eni"
copy /y "bsod_gg2-mapFG.eni" "..\..\..\..\..\..\_gamemode\winBSOD\bsod_gg2-mapFG.eni"
copy /y "bsod_sms1-mapFG.eni" "..\..\..\..\..\..\_gamemode\winBSOD\bsod_sms1-mapFG.eni"
copy /y "bsod_sms2-mapFG.eni" "..\..\..\..\..\..\_gamemode\winBSOD\bsod_sms2-mapFG.eni"
copy /y "bsod_gg-pal.bin" "..\..\..\..\..\..\_gamemode\winBSOD\bsod_gg-pal.bin"
copy /y "bsod_sms-pal.bin" "..\..\..\..\..\..\_gamemode\winBSOD\bsod_sms-pal.bin"
REM pause