cls
call KENSSharp.exe -d k "ARZ.kos" "ARZ.unc"
call KENSSharp.exe -d k "BSZ.bin" "BSZ.unc"
call KENSSharp.exe -d k "Bluestone.kos" "Bluestone.unc"
call KENSSharp.exe -d k "BREW.kos" "BREW.unc"
call KENSSharp.exe -d k "BTZ.kos" "BTZ.unc"
call KENSSharp.exe -d k "DVZ.kos" "DVZ.unc"
call KENSSharp.exe -d k "DVZ3.kos" "DVZ3.unc"
call KENSSharp.exe -d k "GHZ.kos" "GHZ.unc"
call KENSSharp.exe -d k "HSZ.kos" "HSZ.unc"
call KENSSharp.exe -d k "Joint.kos" "Joint.unc"
call KENSSharp.exe -d k "LZ.kos" "LZ.unc"
call KENSSharp.exe -d k "MVZ (JP1).kos" "MVZ (JP1).unc"
call KENSSharp.exe -d k "MVZ.kos" "MVZ.unc"
call KENSSharp.exe -d k "MZ (JP1).kos" "MZ (JP1).unc"
call KENSSharp.exe -d k "MZ.kos" "MZ.unc"
call KENSSharp.exe -d k "NGZ.kos" "NGZ.unc"
call KENSSharp.exe -d k "SBZ (JP1).kos" "SBZ (JP1).unc"
call KENSSharp.exe -d k "SBZ.kos" "SBZ.unc"
call KENSSharp.exe -d k "SLZ.kos" "SLZ.unc"
call KENSSharp.exe -d k "SYZ.kos" "SYZ.unc"
call KENSSharp.exe -d k "WIN.kos" "WIN.unc"
REM pause