cls
call riffstrip.exe "azd_omg.wav"
call riffstrip.exe "Four.wav"
call riffstrip.exe "Boost.wav"
call riffstrip.exe "BoostR.wav"
call riffstrip.exe "chord16.wav"
call riffstrip.exe "chr_mddio_laugh.wav"
call riffstrip.exe "chr_tonic_burp.wav"
call riffstrip.exe "chr_maniac_laugh.wav"
call riffstrip.exe "disclaimer.wav"
call riffstrip.exe "sb_developers.wav"
call riffstrip.exe "sb_love.wav"
call riffstrip.exe "sb_pc.wav"
call riffstrip.exe "EagleSoft_Song.wav"
call riffstrip.exe "eggmanLaugh.wav"
call riffstrip.exe "GenesisCan1.wav"
call riffstrip.exe "GenesisCan2.wav"
call riffstrip.exe "GenesisCan3.wav"
call riffstrip.exe "GenesisDoes1.wav"
call riffstrip.exe "git-hub.wav"
call riffstrip.exe "Madness.wav"
call riffstrip.exe "MadnessR.wav"
call riffstrip.exe "meow.wav"
call riffstrip.exe "prngCan.wav"
call riffstrip.exe "prngChip.wav"
call riffstrip.exe "prngUgh.wav"

call riffstrip.exe "shutdown.wav"
call riffstrip.exe "udied.wav"
REM call riffstrip.exe "nep.wav"
REM call riffstrip.exe "SM64_MM.wav"
call riffstrip.exe "Virus_Alert.wav"
call riffstrip.exe "w95r_better.wav"
call riffstrip.exe "w95r_changeLife.wav"
call riffstrip.exe "w95r_gates.wav"
call riffstrip.exe "w95r_live.wav"
call riffstrip.exe "w95r_microsoft.wav"
call riffstrip.exe "w95r_mouse.wav"
call riffstrip.exe "w95r_much.wav"
call riffstrip.exe "w95r_neverbeaten.wav"
call riffstrip.exe "w95r_ooh1.wav"
call riffstrip.exe "w95r_ooh2.wav"
call riffstrip.exe "w95r_ooh3.wav"
call riffstrip.exe "w95r_ooh4.wav"
call riffstrip.exe "w95r_w95.wav"
call riffstrip.exe "w95r_w95_2.wav"
call riffstrip.exe "w95r_windows.wav"
call riffstrip.exe "w98ipc.wav"
call riffstrip.exe "windie.wav"
call riffstrip.exe "YoFreddy.wav"

ren "azd_omg.wav.stripped" "azd_omg.pcm"
ren "Four.wav.stripped" "Four.pcm"
ren "Boost.wav.stripped" "Boost.pcm"
ren "BoostR.wav.stripped" "BoostR.pcm"
ren "chord16.wav.stripped" "chord16.pcm"
ren "chr_mddio_laugh.wav" "chr_mddio_laugh.pcm"
ren "chr_tonic_burp.wav" "chr_tonic_burp.pcm"
ren "chr_maniac_laugh.wav" "chr_maniac_laugh.pcm"
ren "disclaimer.wav.stripped" "disclaimer.pcm"
ren "sb_developers.wav.stripped" "sb_developers.pcm"
ren "sb_love.wav.stripped" "sb_love.pcm"
ren "sb_pc.wav.stripped" "sb_pc.pcm"
ren "EagleSoft_Song.wav.stripped" "EagleSoft_Song.pcm"
ren "eggmanLaugh.wav.stripped" "eggmanLaugh.pcm"
ren "GenesisCan1.wav.stripped" "GenesisCan1.pcm"
ren "GenesisCan2.wav.stripped" "GenesisCan2.pcm"
ren "GenesisCan3.wav.stripped" "GenesisCan3.pcm"
ren "GenesisDoes1.wav.stripped" "GenesisDoes1.pcm"
ren "git-hub.wav.stripped" "git-hub.pcm"
ren "Madness.wav.stripped" "Madness.pcm"
ren "MadnessR.wav.stripped" "MadnessR.pcm"
ren "meow.wav.stripped" "meow.pcm"
ren "prngCan.wav.stripped" "prngCan.pcm
ren "prngChip.wav.stripped" "prngChip.pcm
ren "prngUgh.wav.stripped" "prngUgh.pcm

ren "shutdown.wav.stripped" "shutdown.pcm"
ren "udied.wav.stripped" "udied.pcm"
REM ren "nep.wav.stripped" "nep.pcm"
REM ren "SM64_MM.wav.stripped" "SM64_MM.pcm"
ren "Virus_Alert.wav.stripped" "Virus_Alert.pcm"
ren "w95r_gates.wav.stripped" "w95r_gates.pcm"
ren "w95r_live.wav.stripped" "w95r_live.pcm"
ren "w95r_microsoft.wav.stripped" "w95r_microsoft.pcm"
ren "w95r_mouse.wav.stripped" "w95r_mouse.pcm"
ren "w95r_much.wav.stripped" "w95r_much.pcm"
ren "w95r_neverbeaten.wav.stripped" "w95r_neverbeaten.pcm"
ren "w95r_ooh1.wav.stripped" "w95r_ooh1.pcm"
ren "w95r_ooh2.wav.stripped" "w95r_ooh2.pcm"
ren "w95r_ooh3.wav.stripped" "w95r_ooh3.pcm"
ren "w95r_ooh4.wav.stripped" "w95r_ooh4.pcm"
ren "w95r_w95.wav.stripped" "w95r_w95.pcm"
ren "w95r_w95_2.wav.stripped" "w95r_w95_2.pcm"
ren "w95r_windows.wav.stripped" "w95r_windows.pcm"
ren "w95r_better.wav.stripped" "w95r_better.pcm"
ren "w95r_changeLife.wav.stripped" "w95r_changeLife.pcm"
ren "w98ipc.wav.stripped" "w98ipc.pcm"
ren "windie.wav.stripped" "windie.pcm"
ren "YoFreddy.wav.stripped" "YoFreddy.pcm"

del /q "azd_omg.wav.stripped"
del /q "Four.wav.stripped"
del /q "Boost.wav.stripped"
del /q "BoostR.wav.stripped"
del /q "chord16.wav.stripped"
del /q "chr_mddio_laugh.wav.stripped"
del /q "chr_tonic_burp.wav.stripped"
del /q "chr_maniac_laugh.wav.stripped"
del /q "disclaimer.wav.stripped"
del /q "sb_developers.wav.stripped"
del /q "sb_love.wav.stripped"
del /q "sb_pc.wav.stripped"
del /q "EagleSoft_Song.wav.stripped"
del /q "eggmanLaugh.wav.stripped"
del /q "GenesisCan1.wav.stripped"
del /q "GenesisCan2.wav.stripped"
del /q "GenesisCan3.wav.stripped"
del /q "GenesisDoes1.wav.stripped"
del /q "git-hub.wav.stripped"
del /q "Madness.wav.stripped"
del /q "MadnessR.wav.stripped"
del /q "meow.wav.stripped"
del /q "prngCan.wav.stripped"
del /q "prngChip.wav.stripped"
del /q "prngUgh.wav.stripped"
del /q "shutdown.wav.stripped"
REM del /q "nep.wav.stripped"
REM del /q "SM64_MM.wav.stripped"
del /q "YoFreddy.wav.stripped"
del /q "Virus_Alert.wav.stripped"
del /q "udied.wav.stripped"
del /q "w95r_mouse.wav.stripped"
del /q "w95r_much.wav.stripped"
del /q "w95r_neverbeaten.wav.stripped"
del /q "w95r_ooh1.wav.stripped"
del /q "w95r_ooh2.wav.stripped"
del /q "w95r_ooh3.wav.stripped"
del /q "w95r_ooh4.wav.stripped"
del /q "w95r_w95.wav.stripped"
del /q "w95r_w95_2.wav.stripped"
del /q "w95r_windows.wav.stripped"
del /q "w95r_better.wav.stripped"
del /q "w95r_changeLife.wav.stripped"
del /q "w95r_gates.wav.stripped"
del /q "w95r_live.wav.stripped"
del /q "w95r_microsoft.wav.stripped"
del /q "w98ipc.wav.stripped"
del /q "windie.wav.stripped"

call "..\pcm2dpcm.exe" "azd_omg.pcm" "azd_omg.dpcm"
call "..\pcm2dpcm.exe" "Four.pcm" "Four.dpcm"
call "..\pcm2dpcm.exe" "Boost.pcm" "Boost.dpcm"
call "..\pcm2dpcm.exe" "BoostR.pcm" "BoostR.dpcm"
call "..\pcm2dpcm.exe" "chord16.pcm" "chord16.dpcm"
call "..\pcm2dpcm.exe" "chr_mddio_laugh.pcm" "chr_mddio_laugh.dpcm"
call "..\pcm2dpcm.exe" "chr_tonic_burp.pcm" "chr_tonic_burp.dpcm"
call "..\pcm2dpcm.exe" "chr_maniac_laugh.pcm" "chr_maniac_laugh.dpcm"
call "..\pcm2dpcm.exe" "disclaimer.pcm" "disclaimer.dpcm"
call "..\pcm2dpcm.exe" "sb_developers.pcm" "sb_developers.dpcm"
call "..\pcm2dpcm.exe" "sb_love.pcm" "sb_love.dpcm"
call "..\pcm2dpcm.exe" "sb_pc.pcm" "sb_pc.dpcm"
call "..\pcm2dpcm.exe" "EagleSoft_Song.pcm" "EagleSoft_Song.dpcm"
call "..\pcm2dpcm.exe" "eggmanLaugh.pcm" "eggmanLaugh.dpcm"
call "..\pcm2dpcm.exe" "GenesisCan1.pcm" "GenesisCan1.dpcm"
call "..\pcm2dpcm.exe" "GenesisCan2.pcm" "GenesisCan2.dpcm"
call "..\pcm2dpcm.exe" "GenesisCan3.pcm" "GenesisCan3.dpcm"
call "..\pcm2dpcm.exe" "GenesisDoes1.pcm" "GenesisDoes1.dpcm"
call "..\pcm2dpcm.exe" "git-hub.pcm" "git-hub.dpcm"
call "..\pcm2dpcm.exe" "Madness.pcm" "Madness.dpcm"
call "..\pcm2dpcm.exe" "MadnessR.pcm" "MadnessR.dpcm"
call "..\pcm2dpcm.exe" "meow.pcm" "meow.dpcm"
call "..\pcm2dpcm.exe" "prngCan.pcm" "prngCan.dpcm"
call "..\pcm2dpcm.exe" "prngChip.pcm" "prngChip.dpcm"
call "..\pcm2dpcm.exe" "prngUgh.pcm" "prngUgh.dpcm"
call "..\pcm2dpcm.exe" "shutdown.pcm" "shutdown.dpcm"
call "..\pcm2dpcm.exe" "udied.pcm" "udied.dpcm"
REM call "..\pcm2dpcm.exe" "nep.pcm" "nep.dpcm"
REM call "..\pcm2dpcm.exe" "SM64_MM.pcm" "SM64_MM.dpcm"
call "..\pcm2dpcm.exe" "Virus_Alert.pcm" "Virus_Alert.dpcm"
call "..\pcm2dpcm.exe" "w95r_mouse.pcm" "w95r_mouse.dpcm"
call "..\pcm2dpcm.exe" "w95r_much.pcm" "w95r_much.dpcm"
call "..\pcm2dpcm.exe" "w95r_neverbeaten.pcm" "w95r_neverbeaten.dpcm"
call "..\pcm2dpcm.exe" "w95r_ooh1.pcm" "w95r_ooh1.dpcm"
call "..\pcm2dpcm.exe" "w95r_ooh2.pcm" "w95r_ooh2.dpcm"
call "..\pcm2dpcm.exe" "w95r_ooh3.pcm" "w95r_ooh3.dpcm"
call "..\pcm2dpcm.exe" "w95r_ooh4.pcm" "w95r_ooh4.dpcm"
call "..\pcm2dpcm.exe" "w95r_w95.pcm" "w95r_w95.dpcm"
call "..\pcm2dpcm.exe" "w95r_w95_2.pcm" "w95r_w95_2.dpcm"
call "..\pcm2dpcm.exe" "w95r_windows.pcm" "w95r_windows.dpcm"
call "..\pcm2dpcm.exe" "w95r_better.pcm" "w95r_better.dpcm"
call "..\pcm2dpcm.exe" "w95r_changeLife.pcm" "w95r_changeLife.dpcm"
call "..\pcm2dpcm.exe" "w95r_gates.pcm" "w95r_gates.dpcm"
call "..\pcm2dpcm.exe" "w95r_live.pcm" "w95r_live.dpcm"
call "..\pcm2dpcm.exe" "w95r_microsoft.pcm" "w95r_microsoft.dpcm"
call "..\pcm2dpcm.exe" "w98ipc.pcm" "w98ipc.dpcm"
call "..\pcm2dpcm.exe" "windie.pcm" "windie.dpcm"
call "..\pcm2dpcm.exe" "YoFreddy.pcm" "YoFreddy.dpcm"
REM pause