cls
call KENSSharp.exe -d e "ARZ.eni" "ARZ.unc"
call KENSSharp.exe -d e "BlueStone.eni" "BlueStone.unc"
call KENSSharp.exe -d e "BREW.eni" "BREW.unc"
call KENSSharp.exe -d e "BSZ.bin" "BSZ.unc"
call KENSSharp.exe -d e "BTZ.eni" "BTZ.unc"
call KENSSharp.exe -d e "DVZ.eni" "DVZ.unc"
call KENSSharp.exe -d e "DVZ3.eni" "DVZ3.unc"
call KENSSharp.exe -d e "GHZ.eni" "GHZ.unc"
call KENSSharp.exe -d e "HSZ.eni" "HSZ.unc"
call KENSSharp.exe -d e "Joint.eni" "Joint.unc"
call KENSSharp.exe -d e "LZ.eni" "LZ.unc"
call KENSSharp.exe -d e "MVZ.eni" "MVZ.unc"
call KENSSharp.exe -d e "MZ.eni" "MZ.unc"
call KENSSharp.exe -d e "NGZ.eni" "NGZ.unc"
call KENSSharp.exe -d e "SBZ.eni" "SBZ.unc"
call KENSSharp.exe -d e "SLZ.eni" "SLZ.unc"
call KENSSharp.exe -d e "SYZ.eni" "SYZ.unc"
call KENSSharp.exe -d e "WIN.eni" "WIN.unc"
REM pause