cls
call KENSSharp.exe -c n "g1-art.unc" "g1-art.nem"
call KENSSharp.exe -c n "g2-art.unc" "g2-art.nem"
call KENSSharp.exe -c n "g3-art.unc" "g3-art.nem"
call KENSSharp.exe -c n "m1-art.unc" "m1-art.nem"
call KENSSharp.exe -c n "m2-art.unc" "m2-art.nem"
call KENSSharp.exe -c n "m3-art.unc" "m3-art.nem"
call KENSSharp.exe -c n "IV-art.unc" "IV-art.nem"
call KENSSharp.exe -c e "g1-map.unc" "g1-map.eni"
call KENSSharp.exe -c e "g2-map.unc" "g2-map.eni"
call KENSSharp.exe -c e "g3-map.unc" "g3-map.eni"
call KENSSharp.exe -c e "m1-map.unc" "m1-map.eni"
call KENSSharp.exe -c e "m2-map.unc" "m2-map.eni"
call KENSSharp.exe -c e "m3-map.unc" "m3-map.eni"
call KENSSharp.exe -c e "IV-map.unc" "IV-map.eni"
copy /y "g1-art.nem" "..\..\ATOGKTitle\Nemesis\g1-art.nem"
copy /y "g2-art.nem" "..\..\ATOGKTitle\Nemesis\g2-art.nem"
copy /y "g3-art.nem" "..\..\ATOGKTitle\Nemesis\g3-art.nem"
copy /y "m1-art.nem" "..\..\ATOGKTitle\Nemesis\m1-art.nem"
copy /y "m2-art.nem" "..\..\ATOGKTitle\Nemesis\m2-art.nem"
copy /y "m3-art.nem" "..\..\ATOGKTitle\Nemesis\m3-art.nem"
copy /y "IV-art.nem" "..\..\ATOGKTitle\Nemesis\IV-art.nem"
copy /y "g1-map.eni" "..\..\ATOGKTitle\Enigma\g1-map.eni"
copy /y "g2-map.eni" "..\..\ATOGKTitle\Enigma\g2-map.eni"
copy /y "g3-map.eni" "..\..\ATOGKTitle\Enigma\g3-map.eni"
copy /y "m1-map.eni" "..\..\ATOGKTitle\Enigma\m1-map.eni"
copy /y "m2-map.eni" "..\..\ATOGKTitle\Enigma\m2-map.eni"
copy /y "m3-map.eni" "..\..\ATOGKTitle\Enigma\m3-map.eni"
copy /y "IV-map.eni" "..\..\ATOGKTitle\Enigma\IV-map.eni"
copy /y "logo2a-pal.bin" ""..\..\ATOGKTitle\Palette\g2-pal.bin"
copy /y "logo2b-pal.bin" ""..\..\ATOGKTitle\Palette\m2-pal.bin"
copy /y "logo13ab_1c-pal.bin" ""..\..\ATOGKTitle\Palette\text.bin"
pause