cls
call KENSSharp.exe -c n "bsod_scd1-art.unc" "bsod_scd1-art.nem"
call KENSSharp.exe -c e "bsod_scd1-mapFG.unc" "bsod_scd1-mapFG.eni"
call KENSSharp.exe -c n "bsod_scd2-art.unc" "bsod_scd2-art.nem"
call KENSSharp.exe -c e "bsod_scd2-mapFG.unc" "bsod_scd2-mapFG.eni"
call KENSSharp.exe -c n "bsod_scd3-art.unc" "bsod_scd3-art.nem"
call KENSSharp.exe -c e "bsod_scd3-mapFG.unc" "bsod_scd3-mapFG.eni"
call KENSSharp.exe -c n "bsod_scd4-art.unc" "bsod_scd4-art.nem"
call KENSSharp.exe -c e "bsod_scd4-mapFG.unc" "bsod_scd4-mapFG.eni"
call KENSSharp.exe -c n "bsod_scd5-art.unc" "bsod_scd5-art.nem"
call KENSSharp.exe -c e "bsod_scd5-mapFG.unc" "bsod_scd5-mapFG.eni"
copy /y "bsod_scd1-art.nem" "..\..\..\..\..\_gamemode\winBSOD\bsod_scd1-art.nem"
copy /y "bsod_scd1-mapFG.eni" "..\..\..\..\..\_gamemode\winBSOD\bsod_scd1-mapFG.eni"
copy /y "bsod_scd1-pal.bin" "..\..\..\..\..\_gamemode\winBSOD\bsod_scd1-pal.bin"
copy /y "bsod_scd2-art.nem" "..\..\..\..\..\_gamemode\winBSOD\bsod_scd2-art.nem"
copy /y "bsod_scd2-mapFG.eni" "..\..\..\..\..\_gamemode\winBSOD\bsod_scd2-mapFG.eni"
copy /y "bsod_scd2-pal.bin" "..\..\..\..\..\_gamemode\winBSOD\bsod_scd2-pal.bin"
copy /y "bsod_scd3-art.nem" "..\..\..\..\..\_gamemode\winBSOD\bsod_scd3-art.nem"
copy /y "bsod_scd3-mapFG.eni" "..\..\..\..\..\_gamemode\winBSOD\bsod_scd3-mapFG.eni"
copy /y "bsod_scd3-pal.bin" "..\..\..\..\..\_gamemode\winBSOD\bsod_scd3-pal.bin"
copy /y "bsod_scd4-art.nem" "..\..\..\..\..\_gamemode\winBSOD\bsod_scd4-art.nem"
copy /y "bsod_scd4-mapFG.eni" "..\..\..\..\..\_gamemode\winBSOD\bsod_scd4-mapFG.eni"
copy /y "bsod_scd4-pal.bin" "..\..\..\..\..\_gamemode\winBSOD\bsod_scd4-pal.bin"
copy /y "bsod_scd5-art.nem" "..\..\..\..\..\_gamemode\winBSOD\bsod_scd5-art.nem"
copy /y "bsod_scd5-mapFG.eni" "..\..\..\..\..\_gamemode\winBSOD\bsod_scd5-mapFG.eni"
copy /y "bsod_scd5-pal.bin" "..\..\..\..\..\_gamemode\winBSOD\bsod_scd5-pal.bin"
REM pause