game=S1 ; can be any game SonLVL supports
mapfmt=Macro ; one of: Binary, ASM, Macro
dplcfmt=ASM
animfmt=ASM
[Eiza]
art=art.bin ; same format as SonLVL, supports multiple files
artcmp=Uncompressed
palette=SONANIPAL.bin:0:0:16
map=Map.asm
dplc=MapDPLC.asm
dplcgame=S1 ; S3K players use S2 format DPLCs
anim=Anim.asm
; not shown: startpal=0 ; starting palette line