cls
call KENSSharp.exe -c n "bsod_turnoff_font-art.unc" "bsod_turnoff_font-art.nem"
call KENSSharp.exe -c n "bsod_turnoff2-art1.unc" "bsod_turnoff2-art1.nem"
call KENSSharp.exe -c e "bsod_turnoff1-mapFG.unc" "bsod_turnoff1-mapFG.eni"
call KENSSharp.exe -c e "bsod_turnoff2-mapFG.unc" "bsod_turnoff2-mapFG.eni"
call KENSSharp.exe -c e "bsod_turnoff3-mapFG.unc" "bsod_turnoff3-mapFG.eni"
call KENSSharp.exe -c e "bsod_turnoff4-mapFG.unc" "bsod_turnoff4-mapFG.eni"
call KENSSharp.exe -c e "bsod_turnoff5-mapBG.unc" "bsod_turnoff5-mapBG.eni"
call KENSSharp.exe -c e "bsod_turnoff5-mapFG.unc" "bsod_turnoff5-mapFG.eni"
call KENSSharp.exe -c e "bsod_turnoff6-mapFG.unc" "bsod_turnoff6-mapFG.eni"
call KENSSharp.exe -c e "bsod_turnoff7-mapFG.unc" "bsod_turnoff7-mapFG.eni"
call KENSSharp.exe -c e "bsod_turnoff8-mapFG.unc" "bsod_turnoff8-mapFG.eni"

copy /y "bsod_turnoff_font-art.nem" "..\..\..\..\..\_gamemode\winBSOD\bsod_turnoff_font-art.nem"
copy /y "bsod_turnoff2-art1.nem" "..\..\..\..\..\_gamemode\winBSOD\bsod_turnoff2-art1.nem"
copy /y "bsod_turnoff1-mapFG.eni" "..\..\..\..\..\_gamemode\winBSOD\bsod_turnoff1-mapFG.eni"
copy /y "bsod_turnoff2-mapFG.eni" "..\..\..\..\..\_gamemode\winBSOD\bsod_turnoff2-mapFG.eni"
copy /y "bsod_turnoff3-mapFG.eni" "..\..\..\..\..\_gamemode\winBSOD\bsod_turnoff3-mapFG.eni"
copy /y "bsod_turnoff4-mapFG.eni" "..\..\..\..\..\_gamemode\winBSOD\bsod_turnoff4-mapFG.eni"
copy /y "bsod_turnoff5-mapBG.eni" "..\..\..\..\..\_gamemode\winBSOD\bsod_turnoff5-mapBG.eni"
copy /y "bsod_turnoff5-mapFG.eni" "..\..\..\..\..\_gamemode\winBSOD\bsod_turnoff5-mapFG.eni"
copy /y "bsod_turnoff6-mapFG.eni" "..\..\..\..\..\_gamemode\winBSOD\bsod_turnoff6-mapFG.eni"
copy /y "bsod_turnoff7-mapFG.eni" "..\..\..\..\..\_gamemode\winBSOD\bsod_turnoff7-mapFG.eni"
copy /y "bsod_turnoff8-mapFG.eni" "..\..\..\..\..\_gamemode\winBSOD\bsod_turnoff8-mapFG.eni"
copy /y "bsod_turnoff_font-pal.bin" "..\..\..\..\..\_gamemode\winBSOD\bsod_turnoff_font-pal.bin"    
copy /y "bsod_turnoff_fontOR-pal.bin" "..\..\..\..\..\_gamemode\winBSOD\bsod_turnoff_fontOR-pal.bin"  
copy /y "bsod_turnoff_fontBSOD-pal.bin" "..\..\..\..\..\_gamemode\winBSOD\bsod_turnoff_fontBSOD-pal.bin"
copy /y "bsod_turnoff2-pal.bin" "..\..\..\..\..\_gamemode\winBSOD\bsod_turnoff2-pal.bin"        
REM pause