cls
copy /y "Boost\Boost.wav" "..\..\..\sound\DAC\GenesisDoes\Boost.wav"
copy /y "BoostR\BoostR.wav" "..\..\..\sound\DAC\GenesisDoes\BoostR.wav"
copy /y "Four\4.wav" "..\..\..\sound\DAC\GenesisDoes\Four.wav"
copy /y "GenesisCan\GenesisCan1.wav" "..\..\..\sound\DAC\GenesisDoes\GenesisCan1.wav"
copy /y "GenesisCan\GenesisCan2.wav" "..\..\..\sound\DAC\GenesisDoes\GenesisCan2.wav"
copy /y "GenesisCan\GenesisCan3.wav" "..\..\..\sound\DAC\GenesisDoes\GenesisCan3.wav"
copy /y "GenesisDoes1\GenesisDoes.wav" "..\..\..\sound\DAC\GenesisDoes\GenesisDoes1.wav"
copy /y "Meow\meow.wav" "..\..\..\sound\DAC\GenesisDoes\meow.wav"
copy /y "MMZ_BF_Jap\eggmanLaugh.wav" "..\..\..\sound\DAC\GenesisDoes\eggmanLaugh.wav"
copy /y "MMZ_BF_Jap\git-hub.wav" "..\..\..\sound\DAC\GenesisDoes\git-hub.wav"
copy /y "MMZ_BF_Jap\Madness.wav" "..\..\..\sound\DAC\GenesisDoes\Madness.wav"
copy /y "MMZ_BF_Jap\MadnessR.wav" "..\..\..\sound\DAC\GenesisDoes\MadnessR.wav"
copy /y "SteveBallmer\cs188_SteveBallmer_YTP.wav" "..\..\..\sound\DAC\GenesisDoes\disclaimer.wav"
copy /y "WinZone_Die\chord16.wav" "..\..\..\sound\DAC\GenesisDoes\chord16.wav"
copy /y "WinZone_Die\Virus_Alert.wav" "..\..\..\sound\DAC\GenesisDoes\Virus_Alert.wav"
copy /y "WinZone_Die\w98ipc.wav" "..\..\..\sound\DAC\GenesisDoes\w98ipc.wav"
copy /y "WinZone_Die\windie.wav" "..\..\..\sound\DAC\GenesisDoes\windie.wav"
copy /y "WinZone_Die\windows-xp-shutdown.wav" "..\..\..\sound\DAC\GenesisDoes\shutdown.wav"
copy /y "MMZ_BF_Jap\YoFreddy_Rendered.wav" "..\..\..\sound\DAC\GenesisDoes\YoFreddy.wav"
REM pause